[ui]
paginate = "never"
default-command = "log"

[user]
name = "z"
email = "z@local"
username = "z"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[revset-aliases]
'searchPR(x)' = 'fork_point(x-)..x ~ x'
